name: BP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  URI: https://bp-x00192332-qa.azurewebsites.net/

jobs:
  build_and_unit_test:
    name: Build, Run Unit and Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2

      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Build Project - net5.0
        run: dotnet build --configuration Release --no-restore
        
      - name: Run Unit Tests - xUnit
        run: dotnet test BPCalculator.UnitTests/BPCalculator.UnitTests.csproj -c Release --no-build --verbosity normal -l:trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[BPCalculator.Views]*"
        
      - name: Run Acceptance Tests - BDD SpecFlow
        run: dotnet test BPCalculator.AcceptanceTests/BPCalculator.AcceptanceTests.csproj -c Release --no-build --verbosity normal -l:trx

      - name: Generate Code Coverage Report - Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          name: BloodPressureCalculator
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy_and_run_performance_tests:
    name: Deploy to Staging, Run E2E and Performance Tests, Swap Slot
    needs: build_and_unit_test
    environment:
      name: QA
      url: https://gc-bmicalculator-qa-staging.azurewebsites.net
    runs-on: ubuntu-latest
    steps:
      - name: Publish Application
        run: dotnet publish -c Release --no-build -o './BP'

      - name: Azure Login
        uses: Azure/login@v1.4.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Deploy to Azure - QA
        uses: azure/webapps-deploy@v2
        with:
          app-name: BP-X00192332
          slot-name: qa
          package: './BP'

      - name: Run E2E Tests - Selenium
        run: dotnet test BPCalculator.E2ETests/BPCalculator.E2ETests.csproj -c Release --no-build --verbosity normal --logger:"trx;LogFileName=selenium.trx"

      - name: Generate Tests Report
        uses: dorny/test-reporter@v1.5.0
        with:
          name: Tests Report
          path: '**.trx'
          reporter: 'dotnet-trx'

  static_analysis_and_dependency_checker:
    name: Run Static Analysis and Dependency Checker
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Code Static Analysis - SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=dan-lopes
            -Dsonar.projectKey=dan-lopes_csd-ca1

      - name: Run Dependency Checker
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'BP'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7

      - name: Upload Dependency Check Results
        uses: actions/upload-artifact@master
        with:
          name: Dependency Checker Report
          path: ${{github.workspace}}/reports

  security_scan:
    name: Run Security Scan
    runs-on: ubuntu-latest
    needs: deploy_and_run_performance_tests
    steps:
      - name: Pull Docker image for OWASP ZAP
        run: docker pull owasp/zap2docker-weekly

      - name: Run Security Scan - OWASP ZAP
        run: docker run -v /report:/zap/wrk/:rw --user root -t owasp/zap2docker-weekly zap-baseline.py -t ${{env.URI}} -I -r owasp_zap_report.html

      - uses: actions/upload-artifact@v2
        name: Upload OWASP ZAP Report
        with:
          name: OWASP ZAP Report
          path: /report/owasp_zap_report.html