name: BP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2

      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Build Project - net5.0
        run: dotnet build --configuration Release --no-restore
        
      - name: Run Unit Tests - xUnit
        run: dotnet test BPCalculator.UnitTests/BPCalculator.UnitTests.csproj --configuration Release --no-restore --verbosity normal
        
      - name: Run Acceptance Tests - BDD SpecFlow
        run: dotnet test BPCalculator.AcceptanceTests/BPCalculator.AcceptanceTests.csproj --configuration Release --no-restore --verbosity normal        

      - name: Publish
        run: dotnet publish -c Release  -o './BP'

      - name: Azure Login
        uses: Azure/login@v1.4.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Deploy to Azure 
        uses: azure/webapps-deploy@v2
        with:
          app-name: BP-X00192332
          package: './BP'
