name: BP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2

      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Build Project
        run: dotnet build --configuration Release --no-restore
        
      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-restore --verbosity normal
        
      - name: Run SpecFlow Tests
        uses: cryptic-wizard/run-specflow-tests@v1.2.0
        with:
          test-assembly-dll: BPCalculator.BDDTests\bin\Debug\net5.0\BPCalculator.BDDTests.dll
          test-execution-json: BPCalculator.BDDTests\bin\Debug\net5.0\specflow.json
          framework: net5.0
          no-build: true

      - name: Publish
        run: dotnet publish -c Release  -o './BP'

      - name: Azure Login
        uses: Azure/login@v1.4.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Deploy to Azure 
        uses: azure/webapps-deploy@v2
        with:
          app-name: BP-X00192332
          package: './BP'
